### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by onsails** [onsails/lspkind-nvim#1]
- [ ] Field
- [ ] Reference
- [ ] Event
- [ ] Operator
- [ ] TypeParameter

**Comment by beauwilliams** [comment]
Buffer suggestions also seem to be missing

**Comment by onsails** [comment]
> Buffer suggestions also seem to be missing

Correct me if I'm wrong but lsp doesn't complete buffer keywords and its menu label is configured by completion plugin of your choice (nvim-compe, completion-nvim, etc).

**Comment by beauwilliams** [comment]
Ah yes no that is my bad then. I will take a look at compe docs

**Comment by Shatur95** [comment]
@onsails, are you planning to add it?

**Comment by onsails** [comment]
> @onsails, are you planning to add it?

yep, just in my workflows I don't meet such completion candidates so I can't come up with good symbols. PR welcome.

**Comment by astier** [comment]
How about  for Event? It is similar to what vscode is using. You can find it by searching for symbol-event on their [icon-reference site](https://code.visualstudio.com/api/references/icons-in-labels). Btw, where do you usually find icons? I know only about:

- https://fontawesome.com/
- https://www.nerdfonts.com/cheat-sheet

**Comment by onsails** [comment]
nerd-fonts is the default now which relies on nerf-fonts

**Comment by jsgv** [comment]
Where can I install the default font from?
