### ISSUE TITLE
New class-icon

### ISSUE THREAD

**Issue by astier** [onsails/lspkind-nvim#11]
I find the current class- icon `` a little bit washed out and ambiguous. What about ``?

**Comment by onsails** [comment]
Thank you very much for looking into this. Could you please put all your suggestions in a single PR?

**Comment by astier** [comment]
Oh you meant a PR not issue. I somehow misread. Anyway I created a new issue which summarizes all of my suggestions. I won't create a PR since I don't use lspkind myself. I configure the kinds myself.
