### ISSUE TITLE
possible to resize/auto resize the completion window?

### ISSUE THREAD

**Issue by shaeinst** [onsails/lspkind-nvim#13]
as you can see in screenshot, size of the window is according to length of suggested item having max length.
so is there any way to display custom/limit lenght of suggested items?

![image](https://user-images.githubusercontent.com/41078534/125168204-fc23a980-e1c3-11eb-8456-b41cb210c491.png)
![image](https://user-images.githubusercontent.com/41078534/125168031-24f76f00-e1c3-11eb-8a81-a6e0da87ec59.png)

**Comment by onsails** [comment]
All this plugin [does](https://github.com/onsails/lspkind-nvim/blob/master/lua/lspkind/init.lua#L100) it just replace default CompletionItemKinds with the ones with icons. This plugin doesn't control autocomplete window, I suppose you should look for vim ways for controlling it.
