### ISSUE TITLE
Document font requirements

### ISSUE THREAD

**Issue by mikehaertl** [onsails/lspkind-nvim#23]
Please forgive my ignorance but I'm probably missing something very obvious: The icons don't work at all for me. 

![image](https://user-images.githubusercontent.com/675062/137528735-83cfe50b-a9b9-4797-9139-ce17e9b29c3f.png)

What's weird is that I can not even see any icons in the browser (e.g. on the project's start page on github):

![image](https://user-images.githubusercontent.com/675062/137528806-68688b9c-2319-435d-8a30-01b5e8b3841c.png)

Could you maybe add some notes on which font is required to make this work?

OS: Linux Mint
Neovim 0.5.1

**Comment by onsails** [comment]
I understand your confusion, please take attention to this:
```
    -- can be either 'default' (requires nerd-fonts font) or
    -- 'codicons' for codicon preset (requires vscode-codicons font)
```
in configuration example. There is also an issue #18 to have preset which doesn't require extra font and awesome input from @fenux, however I didn't have a time to properly test this approach.

**Comment by mikehaertl** [comment]
Thanks. I've seen this comment but somehow missed its meaning. Maybe a short introductory note would still be helpful.

Anyway this can be closed then.
