### ISSUE TITLE
Invert `abbr symbol` to `symbol abbr`

### ISSUE THREAD

**Issue by nimeco** [onsails/lspkind-nvim#28]
Greetings,

Is there a way to swap the abbr and symbols? Without text, so it looks like `[] varName`?

Thanks in advance!!

**Comment by onsails** [comment]
currently no, PR is welcome :)

**Comment by nimeco** [comment]
ah, I tried to mess with the code a lil bit but I don't really know how vim does it, still a newbie, gotta study more :p

**Comment by onsails** [comment]
fixed in #35
