### ISSUE TITLE
DEPRECATED replaced by mode option.

### ISSUE THREAD

**Issue by lowstar** [onsails/lspkind-nvim#36]
Hi,

I changed my config to:

```
cmp.setup({
    ...
    formatting = {
        format = require("lspkind").cmp_format({
            mode = "symbol_text",
            maxwidth = 50,
        }),
    },
    ...
})
```

but still getting _"DEPRECATED replaced by mode option"_ message on each attempt to autocomplete. I had to disable lsp-kind because it made cmp unusable.

**Comment by onsails** [comment]
should be fixed now, please check
