### ISSUE TITLE
Using the same icons as VS Code

### ISSUE THREAD

**Issue by Kazy** [onsails/lspkind-nvim#6]
Hello ! 

Following your post on Reddit (thanks for posting it by the way, quite useful !), I actually tried (and succeeded) to obtain the same icons in my terminal than the one used by VS Code. So this post is just to describe how I did it, in case you want to either add it as an option in the plugin, or just mention it as a solution somewhere.

This is done using Kitty, I don't know how to achieve it with an other terminal emulator. It should work for any font.

1. Download the `codicon` font at https://github.com/microsoft/vscode-codicons/blob/master/dist/codicon.ttf and put it in your font folder (usually `~/.local/share/fonts`), followed by a `fc-cache`.
2. In your `kitty.conf`, add this line: `symbol_map U+EA60-U+EBBC codicon`.
3. The kind symbols (with text) now looks like this. I've added two spaces each time between the symbol and the text because the symbols are displayed on two cells.

```
require('vim.lsp.protocol').CompletionItemKind = {
      '  Text';          -- = 1
      '  Function';      -- = 2;
      '  Method';        -- = 3;
      '  Constructor';   -- = 4;
      '  Field';         -- = 5;
      '  Variable';      -- = 6;
      '  Class';         -- = 7;
      '  Interface';     -- = 8;
      '  Module';        -- = 9;
      '  Property';      -- = 10;
      '  Unit';          -- = 11;
      '  Value';         -- = 12;
      '  Enum';          -- = 13;
      '  Keyword';       -- = 14;
      '  Snippet';       -- = 15;
      '  Color';         -- = 16;
      '  File';          -- = 17;
      '  Reference';     -- = 18;
      '  Folder';        -- = 19;
      '  EnumMember';    -- = 20;
      '  Constant';      -- = 21;
      '  Struct';        -- = 22;
      '  Event';         -- = 23;
      '  Operator';      -- = 24;
      '  TypeParameter'; -- = 25;
}
```

I've looked up the symbols on [this webpage](https://code.visualstudio.com/api/references/icons-in-labels). This is the Product Icon Reference for Visual Studio. They are named `symbol-text`, `symbol-function` and so on.

**Comment by onsails** [comment]
Thank you for the manual, it can be handy for anyone who wants 100% match with vscode.
However, I have no intent to achieve this match, the purpose of this plugin is to lower cognitive effort to pick right completion due to icons out of the box, without need to alter system outside of vim environment.
I'll leave this issue open tho, maybe some improvement ideas can grow from here, thanks!

**Comment by rudotriton** [comment]
For anyone on iTerm2, do the same, but instead of changing `kitty.conf`, since you wouldn't have it, change your preferences to use a different font for non-ascii, under `Profiles -> Text`:

<img width="500" alt="Screen Shot" src="https://user-images.githubusercontent.com/14181026/107811429-cabec300-6d76-11eb-8e17-be015cbce8eb.png">

**Comment by dhruvmanila** [comment]
> For anyone on iTerm2, do the same, but instead of changing kitty.conf, since you wouldn't have it, change your preferences to use a different font for non-ascii, under Profiles -> Text:

I tried doing this but as I am using a NerdFont as my main font, this setting will not render the NerdFont icons and instead fall back to codicon which does not include them. If there is any way to combine the two fonts, that would probably solve the problem.

**Comment by kabouzeid** [comment]
@Kazy dude thank you, this is exactly what I was looking for!

**Comment by dhruvmanila** [comment]
Small update:

New icons have been added to the set so the updated map would be: 
```
# https://github.com/microsoft/vscode-codicons/blob/main/dist/codicon.css
symbol_map U+ea60-U+ebd1 codicon
```

Also, for iTerm2 you would have to patch them up manually into your Nerdfont using the font-patcher script present in the nerd-fonts repository.

**Comment by kabouzeid** [comment]
Thanks for the update! Which are the new icons?

**Comment by kabouzeid** [comment]
To be more precise, which of them are completion kind related?

**Comment by kabouzeid** [comment]
Because the spec still only have 25 completion item kinds 

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion

**Comment by dhruvmanila** [comment]
Well, I don't exactly know which are the new ones but you can take a look at the release page: https://github.com/microsoft/vscode-codicons/releases

Also, according to the old mapping, these are the new ones:
https://github.com/microsoft/vscode-codicons/blob/40014cd4f4415cd8aca14c50370c32346473cf6f/dist/codicon.css#L455-L475

**Comment by onsails** [comment]
Can someone post full icons set? I'll make a preset in the plugin.

**Comment by dhruvmanila** [comment]
Do you want something like this? https://github.com/yamatsum/nvim-nonicons/blob/main/lua/nvim-nonicons/mapping.lua

**Comment by onsails** [comment]
I need associations like @Kazy did in the first post.

**Comment by dhruvmanila** [comment]
I'm sorry but I don't quite understand what you want exactly. If you can provide me some details, I might be able to help you.

By associations, do you mean you want the icon and the name of it as mentioned on the [official page](https://code.visualstudio.com/api/references/icons-in-labels).

Also, which first post? The one from this issue or the reddit post? I'm unaware of the reddit post.

**Comment by onsails** [comment]
I mean, like in [this](https://github.com/onsails/lspkind-nvim/issues/6#issue-802755120) post in the current thread.
```
't  Text';
'f  Function';
...
```

**Comment by dhruvmanila** [comment]
Right, but you want for all the icons from the vscode-codicons set?

**Comment by onsails** [comment]
it's enough to just have the ones are listed [in readme](https://github.com/onsails/lspkind-nvim#configuration)

**Comment by dhruvmanila** [comment]
So, isn't that exactly what op has in the code block or am I misunderstanding this again lol

```
{
      '  Text';          -- = 1
      '  Function';      -- = 2;
      '  Method';        -- = 3;
      '  Constructor';   -- = 4;
      '  Field';         -- = 5;
      '  Variable';      -- = 6;
      '  Class';         -- = 7;
      '  Interface';     -- = 8;
      '  Module';        -- = 9;
      '  Property';      -- = 10;
      '  Unit';          -- = 11;
      '  Value';         -- = 12;
      '  Enum';          -- = 13;
      '  Keyword';       -- = 14;
      '  Snippet';       -- = 15;
      '  Color';         -- = 16;
      '  File';          -- = 17;
      '  Reference';     -- = 18;
      '  Folder';        -- = 19;
      '  EnumMember';    -- = 20;
      '  Constant';      -- = 21;
      '  Struct';        -- = 22;
      '  Event';         -- = 23;
      '  Operator';      -- = 24;
      '  TypeParameter'; -- = 25;
}
```

or do you want  in this format as that's how you have in the code:
```lua
lsp_kind = {
  Text = "",
  Method = "",
  Function = "",
  Constructor = "",
  Field = "",
  Variable = "",
  Class = "",
  Interface = "",
  Module = "",
  Property = "",
  Unit = "",
  Value = "",
  Enum = "",
  Keyword = "",
  Snippet = "",
  Color = "",
  File = "",
  Reference = "",
  Folder = "",
  EnumMember = "",
  Constant = "",
  Struct = "",
  Event = "",
  Operator = "",
  TypeParameter = "",
}
```

**Comment by onsails** [comment]
> So, isn't that exactly what op has in the code block or am I misunderstanding this again lol
> 
> ```
> {
>       '  Text';          -- = 1
>       '  Function';      -- = 2;
>       '  Method';        -- = 3;
>       '  Constructor';   -- = 4;
>       '  Field';         -- = 5;
>       '  Variable';      -- = 6;
>       '  Class';         -- = 7;
>       '  Interface';     -- = 8;
>       '  Module';        -- = 9;
>       '  Property';      -- = 10;
>       '  Unit';          -- = 11;
>       '  Value';         -- = 12;
>       '  Enum';          -- = 13;
>       '  Keyword';       -- = 14;
>       '  Snippet';       -- = 15;
>       '  Color';         -- = 16;
>       '  File';          -- = 17;
>       '  Reference';     -- = 18;
>       '  Folder';        -- = 19;
>       '  EnumMember';    -- = 20;
>       '  Constant';      -- = 21;
>       '  Struct';        -- = 22;
>       '  Event';         -- = 23;
>       '  Operator';      -- = 24;
>       '  TypeParameter'; -- = 25;
> }
> ```
> 
> or do you want in this format as that's how you have in the code:
> 
> ```lua
> lsp_kind = {
>   Text = "",
>   Method = "",
>   Function = "",
>   Constructor = "",
>   Field = "",
>   Variable = "",
>   Class = "",
>   Interface = "",
>   Module = "",
>   Property = "",
>   Unit = "",
>   Value = "",
>   Enum = "",
>   Keyword = "",
>   Snippet = "",
>   Color = "",
>   File = "",
>   Reference = "",
>   Folder = "",
>   EnumMember = "",
>   Constant = "",
>   Struct = "",
>   Event = "",
>   Operator = "",
>   TypeParameter = "",
> }
> ```

yes, that's what I need. But I suppose github messed up symbols in your comment. Could you upload this mapping to gist?

**Comment by dhruvmanila** [comment]
By messed up, if you mean that you see boxes, then it will render just fine in your terminal with the font installed.

![Screenshot 2021-05-20 at 11 08 19](https://user-images.githubusercontent.com/67177269/118925077-b41e9e00-b95b-11eb-958f-9b15091f0f58.png)

If not, then here's the gist: https://gist.github.com/dhruvmanila/1baa68c0cf985a112391c6deaedb72da

**Comment by onsails** [comment]
> By messed up, if you mean that you see boxes, then it will render just fine in your terminal with the font installed.
> 
> ![Screenshot 2021-05-20 at 11 08 19](https://user-images.githubusercontent.com/67177269/118925077-b41e9e00-b95b-11eb-958f-9b15091f0f58.png)
> 
> If not, then here's the gist: https://gist.github.com/dhruvmanila/1baa68c0cf985a112391c6deaedb72da

oq, that was my Sidekick browser who messed it up. I can copy them from firefox.

**Comment by onsails** [comment]
please check the latest master
