### ISSUE TITLE
Snippet symbol for UltiSnips

### ISSUE THREAD

**Issue by ngmoviedo** [onsails/lspkind-nvim#8]
Could it be possible to add the snippet symbol also for UltiSnips or other snippet engines? I've checked the code, but I don't really know that much about Lua, so I don't know if the solution is trivial or would require some work.
It would be a nice addition, though.

**Comment by onsails** [comment]
There actually [is](https://github.com/onsails/lspkind-nvim/blob/master/lua/lspkind/init.lua#L20) snippet symbol support but only for snippets provided by lsp. The idea of lspkind is to take advantage of neovim's builtin lsp API.

Other completion sources have to be configured either directly using their APIs or via [compiletion engine API](https://github.com/hrsh7th/nvim-compe/pull/223)

**Comment by Melkster** [comment]
I would love it if anyone who's managed to get symbols for all [vim-vsnip](https://github.com/hrsh7th/vim-vsnip/) (or similar) snippets to work to share their config here :)

**Comment by siduck76** [comment]
> I would love it if anyone who's managed to get symbols for all [vim-vsnip](https://github.com/hrsh7th/vim-vsnip/) (or similar) snippets to work to share their config here :)

![image](https://user-images.githubusercontent.com/59060246/123513570-7e33ae80-d6ab-11eb-9796-659a2c6fc30e.png)

**Comment by Melkster** [comment]
@siduck76 Thanks!

**Comment by siduck76** [comment]
It should look like this :)

![image](https://user-images.githubusercontent.com/59060246/123539987-230cc500-d75a-11eb-95c6-8adb2f4d43b4.png)

**Comment by ngmoviedo** [comment]
@siduck76 Thanks! That was what I was trying to achieve too.
